# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7cb3eac58ce9bc14e75d7a8267040a13272476fcf48b177d683b89d3a396ba504ab930b47a03f2fe74ab046ffae439d7eb2a0591c4525f5a2143aeca10c23d2

test:
  secret_key_base: baed1a2cd95e4364436fa6db71e88d630664685239b9ec8ef3447639814bf31e109f07ec50f97e63f6911777623dfea25190b21746661369dfc718714afd0dca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
